meta:
  run_name: lswt_medium_4k8k

model:
  d_model: 1536
  d_ffn: 4096
  n_heads: 24
  n_layers: 18
  n_registers: 0
  recompute_kv: True
  rope_reversed: True
  rope_positions: 4096

train:
  batch_size: 480
  batch_size_step: 2
  batches_per_epoch: 256
  length_sequence: 2048
  length_cache: 2048
  lr_cooldown_tokens: 30000000000