meta:
  run_name: rerope_2k4k

model:
  d_model: 768
  d_ffn: 2048
  n_heads: 12
  n_layers: 12
  n_registers: 0
  recompute_kv: False
  rope_reversed: True
  rope_positions: 4096

train:
  batch_size: 480
  batch_size_step: 6
  batches_per_epoch: 1024
  length_sequence: 2048
  length_cache: 2048
  lr_cooldown_tokens: 10000000000