meta:
  run_name: rope_4k8k

model:
  d_model: 768
  d_ffn: 2048
  n_heads: 12
  n_layers: 12
  n_registers: 0
  recompute_kv: False
  rope_reversed: False
  rope_positions: 8192

train:
  batch_size: 240
  batch_size_step: 3
  batches_per_epoch: 1024
  length_sequence: 4096
  length_cache: 4096
  lr_cooldown_tokens: 10000000000