meta:
  run_name: rope_1k2k

model:
  d_model: 768
  d_ffn: 2048
  n_heads: 12
  n_layers: 12
  n_registers: 0
  recompute_kv: False
  rope_reversed: False
  rope_positions: 2048

train:
  batch_size: 960
  batch_size_step: 12
  batches_per_epoch: 1024
  length_sequence: 1024
  length_cache: 1024
  lr_cooldown_tokens: 10000000000